"""Generate docs/blog-engine/block-schema.md from the schema and the fixture.

    python -m scripts.gen_block_schema_doc

Every attribute table comes from the pydantic models and every example is a
real block from the Phase 1 fixture, so the document cannot disagree with
what the validator accepts. Re-run after changing schema.py.
"""
import json
import os
import sys
import typing

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pydantic import BaseModel  # noqa: E402

from app.blog_engine import schema  # noqa: E402
from app.blog_engine.render import VISUAL_TYPES  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                   "docs", "blog-engine", "block-schema.md")
FIXTURE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "app", "blog_engine", "fixtures", "sample-article.json")

PURPOSE = {
    "paragraph": ("Body text.", "—"),
    "heading": ("h2/h3/h4 only; h1 is the article title.", "auto `id` slug, feeds the TOC"),
    "key_takeaways": ("3–5 bullets, pinned near the top.", "featured snippet / AI overview target"),
    "list": ("bullet, numbered or checklist.", "—"),
    "steps": ("Ordered how-to, optional image per step.", "`HowTo` when ≥3 steps"),
    "image": ("Figure with caption and credit.", "`ImageObject`; alt required"),
    "gallery": ("2–4 images in a grid.", "`ImageObject[]`"),
    "compare_slider": ("Before/after; two images side by side without JS.", "`ImageObject[]`"),
    "video": ("Self-hosted clip or YouTube facade (no iframe until click).", "`VideoObject`"),
    "table": ("Header row, alignment, caption; scroll or stack on mobile.", "table snippet eligible"),
    "callout": ("info / tip / warning / result.", "—"),
    "quote": ("Pull quote with attribution, role, company.", "`Quotation`"),
    "code": ("Language label; copy button appears with JS.", "—"),
    "stat_band": ("2–4 big numbers; count-up with JS.", "—"),
    "chart": ("bar / line / donut from a data table, as inline SVG.", "hidden data table in the DOM"),
    "process_flow": ("Left→right flow with a CSS-animated pulse, as inline SVG.", "hidden ordered list in the DOM"),
    "faq": ("Q/A pairs as a `<details>` accordion.", "`FAQPage`"),
    "cta": ("Link to a service page or Calendly.", "—"),
    "divider": ("Section break: line / dots / glyph.", "—"),
    "embed": ("LinkedIn / X facade — a labelled link, no third-party script.", "—"),
    "legacy_html": ("Migration only. Allowlist-sanitised passthrough.", "—"),
}


def _type_name(annotation) -> str:
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin is typing.Literal:
        return " \\| ".join(f"`{a}`" for a in args)
    if origin is typing.Union or str(origin) == "<class 'types.UnionType'>":
        non_none = [a for a in args if a is not type(None)]
        return _type_name(non_none[0]) + " (optional)" if len(non_none) == 1 else " \\| ".join(_type_name(a) for a in non_none)
    if origin in (list, typing.List):
        return f"list of {_type_name(args[0])}" if args else "list"
    if origin in (dict, typing.Dict):
        return "object"
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return f"[{annotation.__name__}](#{annotation.__name__.lower()})"
    return getattr(annotation, "__name__", str(annotation))


def _rows(model: type) -> str:
    lines = ["| attr | type | default | notes |", "|---|---|---|---|"]
    for name, field in model.model_fields.items():
        if field.is_required():
            default = "required"
        elif field.default_factory is not None:
            default = "`[]`" if field.default_factory is list else "generated"
        elif field.default is None:
            default = "—"
        else:
            try:
                default = f"`{json.dumps(field.default)}`"
            except TypeError:
                default = "generated"
        lines.append(f"| `{name}` | {_type_name(field.annotation)} | {default} | {field.description or ''} |")
    return "\n".join(lines)


def main() -> int:
    with open(FIXTURE, "r", encoding="utf-8") as fh:
        fixture = json.load(fh)
    example_for = {}
    for b in fixture["blocks"]:
        example_for.setdefault(b["type"], b)

    # Map type -> block model via the discriminated union.
    union = typing.get_args(schema.Block)[0]
    models = {typing.get_args(m.model_fields["type"].annotation)[0]: m for m in typing.get_args(union)}

    out = ["# Block schema", "",
           "Generated by `python -m scripts.gen_block_schema_doc` from `app/blog_engine/schema.py` "
           "and the Phase 1 fixture. Do not edit by hand — change the schema and regenerate.", "",
           "## Envelope", "",
           "```json", json.dumps({"id": "blk_7f3a", "type": "image", "version": 1, "attrs": {}, "content": []}, indent=2), "```", "",
           "- `id` — stable across edits, `blk_` + 4–24 alphanumerics, unique within the article. Used for anchors, comments and revision diffs.",
           "- `type` — one of the 21 types below.",
           "- `version` — schema version of this block, currently `1`.",
           "- `attrs` — per-type attributes (tables below).",
           "- `content` — per-type body: rich text, items, rows, or nothing.", "",
           "## Inline text (rich text)", "",
           "Wherever a block says *rich text*, the value is a list of runs. A bare string or a single run is also accepted and normalised.", "",
           "```json", json.dumps([{"text": "It was just "}, {"text": "slow", "marks": [{"type": "highlight", "attrs": {"token": "amber"}}]}, {"text": "."}], indent=2), "```", "",
           "Marks: " + ", ".join(f"`{m}`" for m in typing.get_args(schema.Mark.model_fields["type"].annotation)) + ".", "",
           "- `link` takes `attrs.href` (http(s), site-relative, `#anchor` or `mailto:`), optional `rel` (`nofollow`, `sponsored`, `ugc`), `target` (`_blank` only), `title`. External links get `rel=\"noopener\"` automatically.",
           f"- `highlight` takes `attrs.token`, one of {', '.join(f'`{t}`' for t in schema.HIGHLIGHT_TOKENS)} — a colour name, never a hex value.",
           f"- `emphasis` takes `attrs.token`, one of {', '.join(f'`{t}`' for t in schema.EMPHASIS_TOKENS)}.",
           "- Every other mark takes no attrs.", "",
           "## Block types", "",
           "| # | type | purpose | SEO output | counts as a visual |", "|---|---|---|---|---|"]
    for i, t in enumerate(schema.BLOCK_TYPES, 1):
        p, s = PURPOSE[t]
        out.append(f"| {i} | `{t}` | {p} | {s} | {'yes' if t in VISUAL_TYPES else '—'} |")
    out.append("")

    for t in schema.BLOCK_TYPES:
        model = models[t]
        out += [f"### `{t}`", "", PURPOSE[t][0], ""]
        attrs_model = model.model_fields["attrs"].annotation
        if isinstance(attrs_model, type) and issubclass(attrs_model, BaseModel):
            out += ["**attrs**", "", _rows(attrs_model), ""]
        else:
            out += ["**attrs** — none.", ""]
        content_ann = model.model_fields["content"].annotation
        out += ["**content** — " + _type_name(content_ann).replace("list of Run", "rich text") + ".", ""]
        if t in example_for:
            out += ["```json", json.dumps(example_for[t], ensure_ascii=False, indent=2), "```", ""]

    out += ["## Shared attribute models", ""]
    for m in (schema.ImageAttrs, schema.ImageVariant, schema.Step, schema.ListItem, schema.Stat,
              schema.ChartSeries, schema.FlowNode, schema.FaqItem):
        out += [f"### {m.__name__}", "", (m.__doc__ or "").strip(), "", _rows(m), ""]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    print(f"wrote {OUT} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
