'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import Shell from '@/components/Shell';
import { Card, ErrorBanner } from '@/components/ui';
import {
  apiError,
  APPROVED_MATRIX,
  ArticleType,
  Country,
  COUNTRY_LABELS,
  seoApi,
  Vertical,
  VERTICAL_LABELS,
} from '@/lib/seo';

/** Pull KD / volume / competitor URLs out of a pasted Ubersuggest block. */
function parseUbersuggest(raw: string) {
  const kd = raw.match(/(?:KD|difficulty)\D{0,12}(\d{1,3})/i);
  const volume = raw.match(/(?:volume|searches)\D{0,12}([\d,]{1,12})/i);
  const urls = Array.from(raw.matchAll(/https?:\/\/[^\s,;]+/g)).map((m) => m[0]);
  return {
    kd: kd ? Number(kd[1]) : null,
    volume: volume ? Number(volume[1].replace(/,/g, '')) : null,
    competitors: Array.from(new Set(urls)).slice(0, 10),
  };
}

export default function NewArticlePage() {
  const router = useRouter();
  const [type, setType] = useState<ArticleType>('onpage');
  const [vertical, setVertical] = useState<Vertical>('agentic_ai');
  const [country, setCountry] = useState<Country | ''>('');
  const [keyword, setKeyword] = useState('');
  const [titleHint, setTitleHint] = useState('');
  const [sourceUrl, setSourceUrl] = useState('');
  const [capturedQuestion, setCapturedQuestion] = useState('');
  const [ubersuggest, setUbersuggest] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  const allowed = APPROVED_MATRIX[vertical];
  const parsed = useMemo(() => parseUbersuggest(ubersuggest), [ubersuggest]);

  // Country is only meaningful for onpage, and only within the approved matrix.
  useEffect(() => {
    if (type === 'content' && country) {
      setCountry('');
      setNotice('Content articles have no country lock, so the country was cleared.');
      return;
    }
    if (country && !allowed.includes(country)) {
      setCountry('');
      setNotice(
        `${COUNTRY_LABELS[country]} is not an approved market for ` +
          `${VERTICAL_LABELS[vertical]}, so it was cleared.`,
      );
    }
  }, [type, vertical, country, allowed]);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    if (type === 'onpage' && !country) {
      setError('Onpage articles require an approved country.');
      return;
    }
    setSaving(true);
    try {
      const { data } = await seoApi.generate({
        type,
        vertical,
        country: type === 'onpage' ? country : null,
        primary_keyword: keyword,
        title_hint: titleHint || null,
        source_url: sourceUrl || null,
        captured_question: capturedQuestion || null,
        keyword_difficulty: parsed.kd,
        monthly_search_volume: parsed.volume,
        competitor_urls: parsed.competitors,
        ubersuggest_raw: ubersuggest || null,
      });
      router.push(`/dashboard/seo/articles/edit/?id=${data.id}`);
    } catch (err) {
      setError(apiError(err, 'Draft generation failed.'));
    } finally {
      setSaving(false);
    }
  };

  return (
    <Shell
      title="New article"
      subtitle="The author draft is generated by Claude, then handed to the team to edit."
    >
      <form onSubmit={submit} className="grid grid-cols-1 gap-4 xl:grid-cols-3">
        <div className="space-y-4 xl:col-span-2">
          <Card title="Targeting">
            <ErrorBanner message={error} />
            {notice && (
              <p className="mb-4 rounded-lg border border-warning/40 bg-warning/10 px-3 py-2 text-sm text-warning">
                {notice}
              </p>
            )}

            <fieldset className="mb-4">
              <legend className="label">Article type</legend>
              <div className="flex gap-3">
                {(['onpage', 'content'] as ArticleType[]).map((option) => (
                  <label
                    key={option}
                    className={`flex-1 cursor-pointer rounded-lg border px-4 py-3 text-sm transition-colors ${
                      type === option
                        ? 'border-primary bg-primary/10 text-white'
                        : 'border-line bg-raised text-slate-300 hover:border-slate-500'
                    }`}
                  >
                    <input
                      type="radio"
                      name="type"
                      className="sr-only"
                      checked={type === option}
                      onChange={() => {
                        setType(option);
                        setNotice(null);
                      }}
                    />
                    <span className="block font-medium capitalize">{option}</span>
                    <span className="mt-0.5 block text-xs text-muted">
                      {option === 'onpage'
                        ? 'Country-locked, geo keyword, commercial CTA'
                        : 'General education, no country, informational CTA'}
                    </span>
                  </label>
                ))}
              </div>
            </fieldset>

            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div>
                <label className="label" htmlFor="vertical">
                  Vertical
                </label>
                <select
                  id="vertical"
                  className="input-field"
                  value={vertical}
                  onChange={(e) => {
                    setVertical(e.target.value as Vertical);
                    setNotice(null);
                  }}
                >
                  {Object.entries(VERTICAL_LABELS).map(([key, label]) => (
                    <option key={key} value={key}>
                      {label}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="label" htmlFor="country">
                  Country
                </label>
                <select
                  id="country"
                  className="input-field"
                  value={country}
                  disabled={type === 'content'}
                  onChange={(e) => setCountry(e.target.value as Country | '')}
                >
                  <option value="">
                    {type === 'content' ? 'Not applicable' : 'Select a country'}
                  </option>
                  {allowed.map((c) => (
                    <option key={c} value={c}>
                      {COUNTRY_LABELS[c]}
                    </option>
                  ))}
                </select>
                <p className="mt-1 text-xs text-muted">
                  {type === 'content'
                    ? 'Content articles carry no country lock.'
                    : `Approved for ${VERTICAL_LABELS[vertical]}: ${allowed
                        .map((c) => COUNTRY_LABELS[c])
                        .join(', ')}`}
                </p>
              </div>

              <div>
                <label className="label" htmlFor="keyword">
                  Primary keyword
                </label>
                <input
                  id="keyword"
                  className="input-field"
                  value={keyword}
                  onChange={(e) => setKeyword(e.target.value)}
                  required
                />
              </div>

              <div>
                <label className="label" htmlFor="title-hint">
                  Working title <span className="text-muted">(optional)</span>
                </label>
                <input
                  id="title-hint"
                  className="input-field"
                  value={titleHint}
                  onChange={(e) => setTitleHint(e.target.value)}
                />
              </div>
            </div>
          </Card>

          <Card title="Source">
            <div className="grid grid-cols-1 gap-4">
              <div>
                <label className="label" htmlFor="source-url">
                  Source URL <span className="text-muted">(Reddit / Quora / PAA)</span>
                </label>
                <input
                  id="source-url"
                  className="input-field"
                  value={sourceUrl}
                  onChange={(e) => setSourceUrl(e.target.value)}
                  placeholder="https://www.reddit.com/r/…"
                />
              </div>
              <div>
                <label className="label" htmlFor="question">
                  Captured question
                </label>
                <textarea
                  id="question"
                  className="input-field min-h-[80px]"
                  value={capturedQuestion}
                  onChange={(e) => setCapturedQuestion(e.target.value)}
                  placeholder="The exact question a real person asked. The storyline hook is built from this."
                />
              </div>
            </div>
          </Card>
        </div>

        <div className="space-y-4">
          <Card title="Ubersuggest paste">
            <p className="mb-3 text-xs text-muted">
              Paste the raw Ubersuggest block. KD, volume, and competitor URLs are read out
              of it automatically.
            </p>
            <textarea
              className="input-field min-h-[200px] font-mono text-xs"
              value={ubersuggest}
              onChange={(e) => setUbersuggest(e.target.value)}
              placeholder={'KD 34\nVolume 1,900\nhttps://competitor.com/guide'}
            />
            <dl className="mt-3 space-y-1 text-xs">
              <div className="flex justify-between">
                <dt className="text-muted">Keyword difficulty</dt>
                <dd className="tabular-nums text-slate-200">{parsed.kd ?? '—'}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted">Monthly volume</dt>
                <dd className="tabular-nums text-slate-200">
                  {parsed.volume?.toLocaleString() ?? '—'}
                </dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted">Competitor URLs</dt>
                <dd className="tabular-nums text-slate-200">{parsed.competitors.length}</dd>
              </div>
            </dl>
          </Card>

          <Card>
            <button type="submit" className="btn-primary w-full" disabled={saving}>
              {saving ? 'Generating draft…' : 'Generate author draft'}
            </button>
            <p className="mt-2 text-xs text-muted">
              Costs roughly ₹8-15 per generation and counts against the ₹500/day cap.
            </p>
          </Card>
        </div>
      </form>
    </Shell>
  );
}
